### ISSUE TITLE
Cannot bind argument to parameter 'ApiToken' because it is an empty string

### ISSUE THREAD

**Issue by ColinSainsbury** [halfrubbish/AgileBattery#2]
Not sure if this impacted by the recent Tesla API changes but I get this error when executing the PowerShell:
Get-TeslaEnergySiteId : Cannot bind argument to parameter 'ApiToken' because it is an empty string.
At C:\Users\colin\OneDrive\Documents\AgileBattery-main\AgileBattery.psm1:176 char:62
+ ...   $energySiteId = [string](Get-TeslaEnergySiteId -ApiToken $apiToken)
+                                                                ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TeslaEnergySiteId], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-TeslaEnergySiteId
 
Could not retrieve energy site information, aborting
At C:\Users\colin\OneDrive\Documents\AgileBattery-main\AgileBattery.psm1:180 char:9
+         throw "Could not retrieve energy site information, aborting"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not retri...ation, aborting:String) [], RuntimeExcept 
   ion
    + FullyQualifiedErrorId : Could not retrieve energy site information, aborting

**Comment by halfrubbish** [comment]
How are you invoking it? I checked and my script still seems to be working fine just now.

**Comment by ColinSainsbury** [comment]
I have tried both passing it as a command line argument and by storing it in a file as below.
Invoke-AgileBatteryControl -RefreshTokenPath .\RefreshToken.txt 

Both provide the same result
PS C:\Users\colin\OneDrive\Documents\AgileBattery-main> Invoke-AgileBatteryControl -RefreshTokenPath .\RefreshToken.txt
Get-TeslaEnergySiteId : Cannot bind argument to parameter 'ApiToken' because it is an empty string.
At C:\Users\colin\OneDrive\Documents\AgileBattery-main\AgileBattery.psm1:176 char:62
+ ...   $energySiteId = [string](Get-TeslaEnergySiteId -ApiToken $apiToken)
+                                                                ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TeslaEnergySiteId], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-TeslaEnergySiteId

Could not retrieve energy site information, aborting
At C:\Users\colin\OneDrive\Documents\AgileBattery-main\AgileBattery.psm1:180 char:9
+         throw "Could not retrieve energy site information, aborting"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not retri...ation, aborting:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not retrieve energy site information, aborting
I also tried going back through the token generation process and still no joy.

**Comment by halfrubbish** [comment]
Ah man, it looks like this copy diverged from my local copy, sorry about that. I've updated the file, so you'll need to re-clone it and make sure you've reloaded the module but hopefully it should work.

**Comment by ColinSainsbury** [comment]
OK so that moved things forward but I now get a new error
PS C:\Users\colin\OneDrive\Documents\AgileBattery-main> Invoke-AgileBatteryControl .\AgileBattery.psm1 -RefreshTokenPath .\RefreshToken.txt
Could not retrieve a valid refresh token: The remote server returned an error: (400) Bad Request.
At C:\Users\colin\OneDrive\Documents\AgileBattery-main\AgileBattery.psm1:33 char:9
+         throw "Could not retrieve a valid refresh token: $_"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not retri...0) Bad Request.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not retrieve a valid refresh token: The remote server returned an error: (400) Bad
    Request.

**Comment by halfrubbish** [comment]
Can you try running this:-

`Get-TeslaApiToken -RefreshToken "abcde123RawRefreshTokenGoesHere"`

**Comment by halfrubbish** [comment]
And also double check your token is valid by generating a new one using something like https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613

**Comment by ColinSainsbury** [comment]
Running this command generates a long string response without error. I will generate a new token tomorrow.
Thanks for your support
Colin

**Comment by ColinSainsbury** [comment]
OK all working now thanks. The new token works.

**Comment by halfrubbish** [comment]
Great, glad to hear it.
